### ISSUE TITLE
Issue with direct sum

### ISSUE THREAD

**Issue by ArthurConmy** [Name-Kompsky/tripos#6]
Bases are defined as sets

https://github.com/Name-Kompsky/tripos/blob/b25f58f03cd3a9d0a5d906dd6cefb5149f27f26c/IB/linear_algebra.tex#L217

however later in the lemma on direct sums

https://github.com/Name-Kompsky/tripos/blob/b25f58f03cd3a9d0a5d906dd6cefb5149f27f26c/IB/linear_algebra.tex#L365

this statement is incorrect assuming that B_1 and B_2 are sets as their intersection could be non-trivial (I think that a counterexample would be a vector space of the field of 2 elements which I can construct is there is a doubt) which is a problem in the proof of 3 implies 2 (EDIT).

I think this problem is fixed by defining bases as lists (so B_1 and B_2's union has size |B_1| + |B_2|).

**Comment by ArthurConmy** [comment]
Okay, upon discussion elsewhere I think that this result is true, but the proof is still confusing as to the definition of the union of bases

**Comment by ArthurConmy** [comment]
Wait, counterexample: take V the vector space F_2 over itself. Then if U=W=V then U and W have unique bases, and indeed the union of these two bases if a basis of V. 

So unless union is defined as 'union including duplicates', this is a contradiction to the 3 implies 2 proof.

**Comment by Name-Kompsky** [comment]
Corrected now.
